# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
      machine:
        enabled: true
      steps:
        - run: echo "from gh-pages"
workflows:
  version: 2
  build-all:
    jobs:
      - build
